# NumPy

- **Numerical python**
- Geometrical, calculus, arithmatic
- Collection of similar classes
- Classes are collection of similar variables and methods
- Performing numerical operations in python


- **Saving Code time**
- **No for loops**
- **Faster Execution**
- **Uses less memory over list**

In [ ]:
# Adding 2 lists
a = [1, 2, 3, 4] # a is a list
b = [10, 11, 12, 13] # b is a list

# both lists have same length
# now we want to add these two lists, element by element
print(a + b)


In [ ]:
## rather than adding them together it concatenated it
## so to add them together we have to write a for loop
for item1, item2 in zip(a, b):
    c = item1 + item2
    print (c)


### Data structures
- Scalar
- Vector
- Arrays 
- Matrix (built in)

#### Arrays:
A Python Array is a collection of common type of data structures having elements with same data type. It is used to store collections of data. In Python programming, an arrays are handled by the “array” module. If you create arrays using the array module, elements of the array must be of the same numeric type.

NumPy is used for working with an array. NumPy arrays are called **ndarray** or **N-dimensional arrays** and they store elements of the same type and size.

Majority of other libraries are built-on NumPy


## Importing libraries

- We can not just import libraries and call them directly as some libraries names are big
- Hence, we use alias such as np for numpy (conventional way)

In [ ]:
# pip install numpy

In [4]:
import numpy as np

### Scalar

In [ ]:
a = np.array(5)
print(a)

In [ ]:
a.ndim # number of dimensions

### Vector

In [ ]:
a = np.array([1, 2, 3])
print(a)

In [ ]:
a.ndim

In [ ]:
a = np.array([[1, 2, 3]])
print(a.T) # T is used to transpose the vector

### Matrix

In [11]:
# now we are creating two dimensional array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
a.ndim

2

In [ ]:
# now we are creating two dimensional array
a = np.matrix([(1, 2, 3), (4, 5, 6)])
print(a)


In [ ]:
type(a)

### shape

In [ ]:
a = np.matrix([(1, 2, 3), (4, 5, 6)])
print(a)
a.shape # shape function is used to examine the number of rows and columns

### Array of zeros

In [ ]:
np.zeros(4) # array having value 4 zeros 

In [ ]:
np.zeros((3,4)) # array having value zero with three rows and four columns

### Array of ones

In [ ]:
np.ones(7,dtype=np.int32)

In [ ]:
# Create a multidimensional array of 1


### Array of constant

In [ ]:
np.full((4, 3), 10) # here 4 is no of rows, 3 is no of columns and 10 is a constant value.

### arange

In [ ]:
a = np.arange(24, dtype = float) # similar to range function
print(a.dtype)
print(a)

In [ ]:
np.arange(10, 75) # similar to range function

In [ ]:
np.arange(10, 75, 5) # similar to range function

### arrange z nos btwn x & y

In [ ]:
np.linspace(5,10, 4) # here create 4 different data points between 5 and 10 with equal gap


In [ ]:
np.linspace(2,10, 3)

### Random numbers in ndarrays

In [37]:
np.random.random((2,2)) # two rows and two columns

array([[0.63600284, 0.54243176],
       [0.50916225, 0.30149621]])

In [ ]:
np.random.random((1,7)) # one row and seven columns

In [ ]:
np.random.random((3,3)) # three rows and three columns

### Identity matrix

- An Identity matrix is a square matrix that has 1s along its main diagonal and 0s everywhere else.

In [ ]:
np.eye(4)

In [ ]:
np.eye(4, k = 1)

### The Reshaping of NumPy Arrays

In [ ]:
a = np.array([[2,3,4],[4,5,6]])
print(a)
a.shape=(3,2)
print(a)

### Size of NumPy array

In [ ]:
a = np.array([[2,3,4],[4,5,6]])
print(a)
print(a.size) # how many values there are in the array using the size attribute


### flip

In [ ]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)


In [ ]:
print('Reversed array vertically :','\n',np.flip(a,axis=1))


In [ ]:
print('Reversed array horizontally :','\n',np.flip(a,axis=0))

In [ ]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)


In [ ]:
print('Reversed array :','\n',a[::-1,::-1])

### sort

In [ ]:
a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a)

In [108]:
a = np.array([[5,6,7,4],
              [9,2,3,7]])# sort along the column

print(a)

[[5 6 7 4]
 [9 2 3 7]]


In [109]:
print(np.sort(a, kind='mergresort',axis=1))

[[4 5 6 7]
 [2 3 7 9]]


In [110]:
# sort along the row
print(np.sort(a, kind='mergresort',axis=0))

[[5 2 3 4]
 [9 6 7 7]]


## Basic mathematics using numPy

In [ ]:
# Adding 2 lists
a = [1, 2, 3, 4] # a is a list
b = [10, 11, 12, 13] # b is a list

# both lists have same length
# now we want to add these two lists, element by element
print(a + b)


In [ ]:
a + 10

## Addition using numpy

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4]) # a is an array
# a + 10 # we can simply do all basic mathematics
# a - 10
# a * 10
# a / 10
a // 10

In [ ]:
##type 1
a = np.array([10, 20])
print(a)
np.sum([10,20])

In [ ]:
#type 2
a,b = 10,20
np.sum([a,b])

In [ ]:
#type 3
a = np.array([[1, 2], [3, 1]])
print(a)
np.sum(a, axis=0) # axis o means column wise

In [ ]:
#type 4
a = np.array([[1, 2], [3, 1]])
print(a)
np.sum(a, axis=1) # axis 1 means row wise

In [ ]:
a + 10 # adding a constant value in a matrix

### subtraction using numpy

In [ ]:
np.subtract(10,20)

### other maths functions using numpy

In [ ]:
np.multiply(2,3) #multiply

In [56]:
np.divide(10,5)  #divide

2.0

In [ ]:
#multiply arrays
a = np.array([2,3,4]) 
b = np.array([5,6,3])
np.multiply(a,b) # element wise multiplication

In [ ]:
#exp, sqrt
a=[1,2,4]
print("xyz", np.exp(a))
print("square root :", np.sqrt(a))

### Basic statistics

In [ ]:
age = [23, 34, 27, 30, 32, 31, 33, 26, 28, 25]
np.std(age)

In [ ]:
np.std(age, ddof = 1) # ddof means the Delta Degrees of Freedom. It actually means n - 1

In [ ]:
np.var(age, ddof = 1) # ddof means the Delta Degrees of Freedom. It actually means n - 1

In [ ]:
np.mean(age)

In [ ]:
np.median(age)

In [ ]:
np.min(age)

In [ ]:
np.max(age)

In [100]:
a = np.array([[1,6],
[4,3]])
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

Min : [1 3]
Max : [6 4]


## Boolean indexing

In [ ]:
# What will be the output of following function?
Age = np.array([75, 65, 25, 92, 18, 14, 22])
Age <= 18

In [ ]:
Age_18 = Age[Age <=18]
Age_18

## array comparison

In [ ]:
import numpy as np

# What will be the output of following code?
a = [3,2,3]
b = [3,2,4]
c = [1,2,3]
np.equal(a,b)

In [ ]:
#array wise comparison
a = [1,2,3]
b = [1,2,3]
c = [1,2,4]
np.array_equal(a,c)

## broadcasting
 - the ability of NumPy to treat arrays of different shapes during arithmetic operations

In [ ]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b = np.array([1])
print(a.shape)
print(b.shape)
print('First array: \n',a,'\n')
print('Second array: \n',b,'\n')

print('total of 1st and 2nd : \n\n',a+b)

## Stacking

In [71]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 11, 12, 13])


In [ ]:
print(np.vstack((a, b))) # vertical stacking

In [ ]:
print(np.hstack((a, b))) # horizontal stacking

## concatenate 2 arrays

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

In [ ]:
#combining col-wise
np.column_stack((a,b))

## Splitting Array

In [ ]:
# Syntax: numpy.reshape(array, shape)
x = np.arange(16).reshape(4,4) # first array and then shape
print(x)

In [ ]:
#split the same array horiz - after 2 cols
x = np.arange(16).reshape(4,4)
print(x, "\n\n")
np.hsplit(x,2)

## Indexing & Slicing

In [ ]:
a = ['n','o','p','e','t','o','h','i','m']
a[0:5]

In [82]:
# to slice arrays based on arrays
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [83]:
a[0]

array([1, 2, 3])

In [86]:
# to extract 1st array
a[:1]

array([[1, 2, 3]])

In [ ]:
# to extract, 2nd and 3rd element from 1st array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


In [ ]:
a[:1,1:]

In [ ]:
#to extract only 2,3,5 and 6 from the arrays, i.e.,1st 2 rows (horiz) and after 1st col(vertically)
a[:2,1:]

In [ ]:
#to extract 5,6,8 and 9 from the array
a[1:,1:]

## reading files

In [124]:
peng = np.genfromtxt("penguins_lter.csv", delimiter=",", dtype=str)
peng

array([['studyName', 'Sample_Number', 'Species', ...,
        'Flipper_Length_mm', 'Body_Mass_g', 'Sex'],
       ['PAL0708', '1', 'Adelie', ..., '181', '3750', 'MALE'],
       ['PAL0708', '2', 'Adelie', ..., '186', '3800', 'FEMALE'],
       ...,
       ['PAL0910', '122', 'Gentoo', ..., '222', '5750', 'MALE'],
       ['PAL0910', '123', 'Gentoo', ..., '212', '5200', 'FEMALE'],
       ['PAL0910', '124', 'Gentoo', ..., '213', '5400', 'MALE']],
      dtype='<U17')

In [118]:
peng.shape

(345, 12)

In [121]:
# Unique data
np.unique(peng[...,0])

array(['PAL0708', 'PAL0809', 'PAL0910', 'studyName'], dtype='<U17')

In [122]:
np.unique([peng[...,-1]])

array(['', '.', 'FEMALE', 'MALE', 'Sex'], dtype='<U17')

In [123]:
# Data Filteration
Male = peng[peng[...,-1]=='Male']
Male

array([], shape=(0, 12), dtype='<U17')